### PR TITLE
Update email from beis.gov.uk to businessandtrade.gov.uk

### PR DESCRIPTION
**Pull request by Nashar101**
Description
Changed email from opss.enquiries@beis.gov.uk to opss.enquiries@businessandtrade.gov.uk thought-out the app
Before
image
After
image

### CODE REVIEW

**Review by meeravnagesh — APPROVED** [review]

**Review by alan-at-work — CHANGES_REQUESTED** [review]
Please check the whole project for the beis email address.

There are 13 files, with 27 occurrences with the email

**Comment by Nashar101** [comment]
> Please check the whole project for the beis email address.
> 
> There are 13 files, with 27 occurrences with the email

Changed all occurences

**Comment by alan-at-work** [comment]
> > Please check the whole project for the beis email address.
> > There are 13 files, with 27 occurrences with the email
> 
> Changed all occurences

Still 2 more instances in the main readme doc, on line 7

**Comment by Nashar101** [comment]
> > > Please check the whole project for the beis email address.
> > > There are 13 files, with 27 occurrences with the email
> > 
> > 
> > Changed all occurences
> 
> Still 2 more instances in the main readme doc, on line 7

Sorry my bad, will check now

**Review by alan-at-work — APPROVED** [review]
Looks good, nicely done.

**Pull request merged**
